// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTIMN2k8Q9UZ3DQEKF29GrqOkjKtLMs1o',
    appId: '1:171144512943:web:b897f46c9d5933d1731b5a',
    messagingSenderId: '171144512943',
    projectId: 'athlos-app-a7d69',
    authDomain: 'athlos-app-a7d69.firebaseapp.com',
    storageBucket: 'athlos-app-a7d69.firebasestorage.app',
    measurementId: 'G-0640QT26LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDikTPg1OhdI7hlphyb1Sk4tvrX4SfKRc4',
    appId: '1:171144512943:android:f80517b92b3bc103731b5a',
    messagingSenderId: '171144512943',
    projectId: 'athlos-app-a7d69',
    storageBucket: 'athlos-app-a7d69.firebasestorage.app',
  );
}
